-- 코드를 입력하세요
SELECT HOUR, COUNT(B.DATETIME) AS COUNT
FROM 
(
    SELECT LEVEL-1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL<=24 
)A LEFT JOIN ANIMAL_OUTS B
ON A.HOUR=EXTRACT(HOUR FROM CAST(B.DATETIME AS TIMESTAMP))
GROUP BY HOUR
ORDER BY HOUR
